services:
  frontend:
    build: .
    ports:
      - 3000:3000
    volumes:
     - .:/data/app
     - /data/app/node_modules
    environment:
      NODE_ENV: development
    stdin_open: true
    tty: true
    command: npm run dev
